from __future__ import annotations

import argparse
import csv
import hashlib
import json
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from app.db.connection import get_connection
from scripts.bootstrap_worker_utils import ensure_project_manifest_layout, json_write, timestamp_slug

csv.field_size_limit(min(sys.maxsize, 2**31 - 1))

STAGING_TABLE_DEFAULT = "bgp_bootstrap_staging"
STAGING_COLUMNS = [
    "source",
    "collector",
    "collected_at",
    "peer_ip",
    "peer_asn",
    "prefix",
    "next_hop",
    "as_path",
    "origin_asn",
    "origin_type",
    "med",
    "local_pref",
    "communities",
    "raw_record",
]

LOAD_COLUMNS = STAGING_COLUMNS


@dataclass(frozen=True)
class CsvInspection:
    total_rows: int
    distinct_collectors: int
    distinct_peers: int
    distinct_prefixes: int
    distinct_origin_asns: int
    duplicate_rows: int
    headers: list[str]


def _normalize_text(value: Any) -> str | None:
    if value is None:
        return None
    text = str(value).strip()
    return text or None


def _to_int(value: Any) -> int | None:
    text = _normalize_text(value)
    if text is None:
        return None
    try:
        return int(text)
    except ValueError:
        return None


def _parse_block_metadata(path: Path) -> tuple[int, int]:
    name = path.name
    marker = "_start"
    limit_marker = "_limit"
    if marker not in name or limit_marker not in name:
        raise SystemExit(
            "Não foi possível inferir start-record e limit do nome do arquivo. "
            "Use o padrão bgp_bootstrap_routeviews2_start<START>_limit<LIMIT>.csv"
        )
    start_part = name.split(marker, 1)[1]
    start_text, rest = start_part.split(limit_marker, 1)
    limit_text = rest.split(".", 1)[0]
    return int(start_text), int(limit_text)


def _load_validation(validation_json: Path) -> dict[str, Any]:
    return json.loads(validation_json.read_text(encoding="utf-8"))


def _inspect_csv(csv_path: Path) -> CsvInspection:
    with csv_path.open(encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle)
        headers = list(reader.fieldnames or [])
        seen: set[tuple[str | None, str | None, str | None]] = set()
        total_rows = 0
        duplicate_rows = 0
        distinct_collectors: set[str] = set()
        distinct_peers: set[str] = set()
        distinct_prefixes: set[str] = set()
        distinct_origin_asns: set[int] = set()

        for row in reader:
            total_rows += 1
            collector = _normalize_text(row.get("collector"))
            peer_ip = _normalize_text(row.get("peer_ip"))
            prefix = _normalize_text(row.get("prefix"))
            origin_asn = _to_int(row.get("origin_asn"))

            if collector:
                distinct_collectors.add(collector)
            if peer_ip:
                distinct_peers.add(peer_ip)
            if prefix:
                distinct_prefixes.add(prefix)
            if origin_asn is not None:
                distinct_origin_asns.add(origin_asn)

            key = (collector, peer_ip, prefix)
            if key in seen:
                duplicate_rows += 1
                continue
            seen.add(key)

    return CsvInspection(
        total_rows=total_rows,
        distinct_collectors=len(distinct_collectors),
        distinct_peers=len(distinct_peers),
        distinct_prefixes=len(distinct_prefixes),
        distinct_origin_asns=len(distinct_origin_asns),
        duplicate_rows=duplicate_rows,
        headers=headers,
    )


def _staging_ddl(table_name: str) -> str:
    return f"""
        CREATE TABLE IF NOT EXISTS {table_name} (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            source_file text NOT NULL,
            source_start_record integer NOT NULL,
            source_limit integer NOT NULL,
            source_format text NOT NULL,
            imported_at timestamptz NOT NULL DEFAULT now(),
            source text NOT NULL,
            collector text NOT NULL,
            collected_at timestamptz NULL,
            peer_ip text NULL,
            peer_asn integer NULL,
            prefix text NULL,
            next_hop text NULL,
            as_path text NULL,
            origin_asn integer NULL,
            origin_type text NULL,
            med integer NULL,
            local_pref integer NULL,
            communities text NULL,
            raw_record jsonb NOT NULL
        )
    """


def _ensure_staging_schema(cur, table_name: str) -> None:
    cur.execute(_staging_ddl(table_name))
    cur.execute(f"CREATE INDEX IF NOT EXISTS {table_name}_source_file_idx ON {table_name} (source_file)")
    cur.execute(f"CREATE INDEX IF NOT EXISTS {table_name}_batch_idx ON {table_name} (source_start_record, source_limit)")


def _compare_reports(csv_stats: CsvInspection, validation: dict[str, Any]) -> dict[str, Any]:
    comparison = {
        "total_rows_match": csv_stats.total_rows == int(validation.get("total_rows", -1) or -1),
        "distinct_collectors_match": csv_stats.distinct_collectors
        == int(validation.get("distinct_collectors", -1) or -1),
        "distinct_peers_match": csv_stats.distinct_peers == int(validation.get("distinct_peers", -1) or -1),
        "distinct_prefixes_match": csv_stats.distinct_prefixes == int(validation.get("distinct_prefixes", -1) or -1),
        "distinct_origin_asns_match": csv_stats.distinct_origin_asns
        == int(validation.get("distinct_origin_asns", -1) or -1),
        "duplicate_rows_match": csv_stats.duplicate_rows == int(validation.get("duplicate_rows", -1) or -1),
    }
    comparison["all_match"] = all(comparison.values())
    return comparison


def _write_report_text(report: dict[str, Any], path: Path) -> None:
    lines = [
        f"input={report['input']}",
        f"table_name={report['table_name']}",
        f"mode={report['mode']}",
        f"csv_total_rows={report['csv']['total_rows']}",
        f"csv_distinct_collectors={report['csv']['distinct_collectors']}",
        f"csv_distinct_peers={report['csv']['distinct_peers']}",
        f"csv_distinct_prefixes={report['csv']['distinct_prefixes']}",
        f"csv_distinct_origin_asns={report['csv']['distinct_origin_asns']}",
        f"csv_duplicate_rows={report['csv']['duplicate_rows']}",
        f"validation_total_rows={report['validation']['total_rows']}",
        f"validation_distinct_collectors={report['validation']['distinct_collectors']}",
        f"validation_distinct_peers={report['validation']['distinct_peers']}",
        f"validation_distinct_prefixes={report['validation']['distinct_prefixes']}",
        f"validation_distinct_origin_asns={report['validation']['distinct_origin_asns']}",
        f"validation_duplicate_rows={report['validation']['duplicate_rows']}",
        f"comparison_all_match={report['comparison']['all_match']}",
        f"staging_rows_imported={report['staging'].get('rows_imported')}",
        f"staging_rows_after={report['staging'].get('rows_after')}",
        f"status={report['status']}",
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")


def _copy_columns() -> str:
    return ", ".join(STAGING_COLUMNS)


def _build_copy_sql(table_name: str) -> str:
    return (
        f"COPY {table_name} ({_copy_columns()}) FROM STDIN WITH (FORMAT csv, HEADER true, NULL '')"
    )


def _source_key(input_path: Path) -> str:
    resolved = input_path.resolve()
    digest = hashlib.sha256(str(resolved).encode("utf-8")).hexdigest()[:16]
    return f"{resolved}::{digest}"


def _write_sql_plan(path: Path, table_name: str, csv_path: Path, source_key: str, start_record: int, limit: int) -> None:
    sql = "\n".join(
        [
            f"-- Dry-run only for {csv_path}",
            _staging_ddl(table_name).strip(),
            f"""CREATE TEMP TABLE {table_name}_load (
    source text NOT NULL,
    collector text NOT NULL,
    collected_at timestamptz NULL,
    peer_ip text NULL,
    peer_asn integer NULL,
    prefix text NULL,
    next_hop text NULL,
    as_path text NULL,
    origin_asn integer NULL,
    origin_type text NULL,
    med integer NULL,
    local_pref integer NULL,
    communities text NULL,
    raw_record jsonb NOT NULL
) ON COMMIT DROP;""",
            f"-- Idempotency key: source_file = {source_key}",
            f"DELETE FROM {table_name} WHERE source_file = %s;",
            _build_copy_sql(f"{table_name}_load") + ";",
            f"INSERT INTO {table_name} (source_file, source_start_record, source_limit, source_format, source, collector, collected_at, peer_ip, peer_asn, prefix, next_hop, as_path, origin_asn, origin_type, med, local_pref, communities, raw_record)",
            f"SELECT %s, %s, %s, %s, source, collector, collected_at, peer_ip, peer_asn, prefix, next_hop, as_path, origin_asn, origin_type, med, local_pref, communities, raw_record",
            f"FROM {table_name}_load;",
            "",
            f"-- Source start-record: {start_record}",
            f"-- Source limit: {limit}",
            "",
        ]
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(sql, encoding="utf-8")


def _load_csv_rows_to_staging(
    conn,
    table_name: str,
    csv_path: Path,
    source_key: str,
    start_record: int,
    limit: int,
    source_format: str,
) -> int:
    delete_sql = f"DELETE FROM {table_name} WHERE source_file = %s"
    load_table = f"{table_name}_load"
    copy_sql = _build_copy_sql(load_table)
    insert_sql = f"""
        INSERT INTO {table_name} (
            source_file, source_start_record, source_limit, source_format,
            source, collector, collected_at, peer_ip, peer_asn, prefix,
            next_hop, as_path, origin_asn, origin_type, med, local_pref,
            communities, raw_record
        )
        SELECT
            %s, %s, %s, %s,
            source, collector, collected_at, peer_ip, peer_asn, prefix,
            next_hop, as_path, origin_asn, origin_type, med, local_pref,
            communities, raw_record
        FROM {load_table}
    """
    inserted = 0

    with conn.transaction():
        with conn.cursor() as cur:
            _ensure_staging_schema(cur, table_name)
            cur.execute(f"select count(*) from {table_name} where source_file = %s", (source_key,))
            rows_before = int(cur.fetchone()[0])
            cur.execute(delete_sql, (source_key,))
            cur.execute(
                f"""
                    CREATE TEMP TABLE {load_table} (
                        source text NOT NULL,
                        collector text NOT NULL,
                        collected_at timestamptz NULL,
                        peer_ip text NULL,
                        peer_asn integer NULL,
                        prefix text NULL,
                        next_hop text NULL,
                        as_path text NULL,
                        origin_asn integer NULL,
                        origin_type text NULL,
                        med integer NULL,
                        local_pref integer NULL,
                        communities text NULL,
                        raw_record jsonb NOT NULL
                    ) ON COMMIT DROP
                """
            )

            with csv_path.open("rb") as handle:
                with cur.copy(copy_sql) as copy:
                    while chunk := handle.read(1024 * 1024):
                        copy.write(chunk)

            cur.execute(
                insert_sql,
                (
                    source_key,
                    start_record,
                    limit,
                    source_format,
                ),
            )
            cur.execute(f"select count(*) from {table_name} where source_file = %s", (source_key,))
            inserted = int(cur.fetchone()[0])

    return inserted, rows_before


def _count_staging_rows(conn, table_name: str, source_key: str) -> int:
    with conn.cursor() as cur:
        cur.execute(f"select count(*) from {table_name} where source_file = %s", (source_key,))
        return int(cur.fetchone()[0])


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Importa um snapshot bootstrap já normalizado para uma staging idempotente via COPY."
    )
    parser.add_argument("--input", required=True, type=Path, help="CSV normalizado de entrada.")
    parser.add_argument(
        "--validation-json",
        required=True,
        type=Path,
        help="JSON de validação gerado junto do CSV.",
    )
    parser.add_argument("--table-name", default=STAGING_TABLE_DEFAULT, help="Tabela staging de destino.")
    parser.add_argument("--sql-out", type=Path, default=None, help="Arquivo SQL de dry-run opcional.")
    parser.add_argument("--report-json", type=Path, default=None, help="Relatório JSON opcional.")
    parser.add_argument("--report-text", type=Path, default=None, help="Relatório TXT opcional.")
    parser.add_argument("--apply", action="store_true", help="Executa o COPY real para a staging.")
    args = parser.parse_args()

    if not args.input.exists():
        raise SystemExit(f"CSV não encontrado: {args.input}")
    if not args.validation_json.exists():
        raise SystemExit(f"JSON de validação não encontrado: {args.validation_json}")

    start_record, limit = _parse_block_metadata(args.input)
    csv_stats = _inspect_csv(args.input)
    validation = _load_validation(args.validation_json)
    comparison = _compare_reports(csv_stats, validation)
    source_key = _source_key(args.input)

    sql_out = args.sql_out or ensure_project_manifest_layout() / f"bootstrap_staging_import_{timestamp_slug()}.sql"
    report_json = args.report_json or (
        PROJECT_ROOT
        / "data"
        / "processed"
        / "bootstrap_worker_reports"
        / f"bgp_bootstrap_routeviews2_start{start_record}_limit{limit}_staging_import.json"
    )
    report_text = args.report_text or report_json.with_suffix(".txt")

    staging_report: dict[str, Any] = {
        "input": str(args.input),
        "validation_json": str(args.validation_json),
        "table_name": args.table_name,
        "start_record": start_record,
        "limit": limit,
        "mode": "APPLY" if args.apply else "DRY_RUN",
        "csv": {
            "total_rows": csv_stats.total_rows,
            "distinct_collectors": csv_stats.distinct_collectors,
            "distinct_peers": csv_stats.distinct_peers,
            "distinct_prefixes": csv_stats.distinct_prefixes,
            "distinct_origin_asns": csv_stats.distinct_origin_asns,
            "duplicate_rows": csv_stats.duplicate_rows,
            "headers": csv_stats.headers,
        },
        "validation": {
            "total_rows": int(validation.get("total_rows", 0) or 0),
            "distinct_collectors": int(validation.get("distinct_collectors", 0) or 0),
            "distinct_peers": int(validation.get("distinct_peers", 0) or 0),
            "distinct_prefixes": int(validation.get("distinct_prefixes", 0) or 0),
            "distinct_origin_asns": int(validation.get("distinct_origin_asns", 0) or 0),
            "duplicate_rows": int(validation.get("duplicate_rows", 0) or 0),
        },
        "comparison": comparison,
        "staging": {
            "table_name": args.table_name,
            "source_key": source_key,
            "sql_out": str(sql_out),
        },
        "status": "DRY_RUN_READY" if not args.apply else "PENDING_APPLY",
    }

    _write_sql_plan(sql_out, args.table_name, args.input, source_key, start_record, limit)

    if args.apply:
        with get_connection() as conn:
            rows_imported, rows_before = _load_csv_rows_to_staging(
                conn=conn,
                table_name=args.table_name,
                csv_path=args.input,
                source_key=source_key,
                start_record=start_record,
                limit=limit,
                source_format="csv",
            )
            rows_after = _count_staging_rows(conn, args.table_name, source_key)
            staging_report["staging"]["rows_imported"] = rows_imported
            staging_report["staging"]["rows_after"] = rows_after
            staging_report["staging"]["rows_before"] = rows_before
            staging_report["staging"]["rows_deleted_before_copy"] = rows_before
            staging_report["status"] = "STAGING_IMPORTED"
            staging_report["comparison"]["all_match"] = staging_report["comparison"]["all_match"] and rows_imported == csv_stats.total_rows
            if rows_imported != csv_stats.total_rows:
                staging_report["status"] = "FAILED"
                raise SystemExit(
                    f"Import mismatch: imported_rows={rows_imported} csv_total_rows={csv_stats.total_rows}"
                )
    else:
        staging_report["staging"]["rows_imported"] = 0
        staging_report["staging"]["rows_after"] = 0

    json_write(report_json, staging_report)
    _write_report_text(staging_report, report_text)

    print(json.dumps(staging_report, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
